### ISSUE TITLE
public client application (.net core console) throws AADSTS7000218 exception

### ISSUE THREAD

**Issue by harrchen88** [Azure-Samples/ms-identity-dotnet-desktop-tutorial#16]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>The code in the documentation doesn't work.

### Any log messages given by the failure
>Error message:
A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 30256922-4a47-415b-9351-2493b82f2500
Correlation ID: 207f3b5e-582d-4560-b62f-43a2651b5654
Timestamp: 2023-06-15 13:04:22Z

### Expected/desired behavior
>a user token is received

### OS and Version?
> Windows 11 Enterprise 
### Versions
>OS build: 22621.1848
"Microsoft.Identity.Client" Version="4.49.1"
![publicapplicationerror](https://github.com/Azure-Samples/ms-identity-dotnet-desktop-tutorial/assets/39616938/81163aea-6c6a-4163-b166-1b35e087f854)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@harrchen88 this typically happens when you misconfigure the app type for redirect uri settings (under the Authentication blade) on app registration portal. Can you confirm that you have followed the [instructions given here](https://github.com/Azure-Samples/ms-identity-dotnet-desktop-tutorial/blob/master/1-Calling-MSGraph/1-1-AzureAD/README.md#register-the-client-app-console-interactive-multitarget-v2)? Also feel free share your app manifest.
